### ISSUE TITLE
Open other content closes application

### ISSUE THREAD

**Issue by cipherboy** [OpenSCAP/scap-workbench#169]
When choosing other content to open, if the other content is not a valid input file (e.g., a JPG), the user will be prompted to select another file. If they then press "cancel" in the file selection dialogue, it will close the application, with the message:

```
14:59:49 | info     | Closing the main window...
```

For better UX, the window should stay open with the last-valid profile.

**Comment by cipherboy** [comment]
Fixed by PR #176 / ba141639569a73aa9a3b18d6704fd79e19c93d85

**Comment by matejak** [comment]
I still experience the issue (on Fedora 34), on a codebase that contains the referenced PR. @jan-cerny could you please check out whether the fix works for you or not any more?
